server:
  port: 8000

spring:
  application:
    name: service-order
  profiles:
    active: dev # 指定激活的环境，与下面的active相对应
  cloud:
    nacos:
      server-addr: 192.168.137.128:8848 # Nacos地址
      config:
        namespace: ${spring.profiles.active:public} # 配置所使用的命名空间，默认值为public


#实现根据命名空间，动态导入相应配置信息
---
spring:
  config: # 配置中心导入
    activate:
      on-profile: dev # 激活开发环境的配置文件
    import:
      - nacos:common.properties?group=order # 配置文件及其所属的组
      - nacos:databases.properties?group=order

---
spring:
  config: # 配置中心导入
    activate:
      on-profile: prod # 激活生产环境的配置文件
    import:
      - nacos:common.properties?group=order # 配置文件及其所属的组
      - nacos:databases.properties?group=order

---
spring:
  config: # 配置中心导入
    activate:
      on-profile: test # 激活测试环境的配置文件
    import:
      - nacos:common.properties?group=order # 配置文件及其所属的组
      - nacos:databases.properties?group=order