spring:
  application:
    name: seata-order
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.137.128:8848
      config:
        import-check:
          enabled: false

server:
  port: 12000
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.witness.order.feign: debug # 配置openfeign日志级别
